In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent=[
    'the glass of milk',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good',
]

In [3]:
sent

['the glass of milk',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
##Define the vocabulary size
voc_size=10000

In [6]:
one_hot_repr=[one_hot(words, voc_size) for words in sent]
one_hot_repr

[[5168, 8796, 4463, 8064],
 [5168, 3651, 4463, 2617],
 [6780, 8764, 6657, 2430, 7711],
 [6780, 8764, 6657, 2430, 1526],
 [8918, 5168, 5564, 4463, 9717],
 [530, 130, 1909, 2430]]

In [8]:
##Word Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedding_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedding_docs)


[[   0    0    0    0 5168 8796 4463 8064]
 [   0    0    0    0 5168 3651 4463 2617]
 [   0    0    0 6780 8764 6657 2430 7711]
 [   0    0    0 6780 8764 6657 2430 1526]
 [   0    0    0 8918 5168 5564 4463 9717]
 [   0    0    0    0  530  130 1909 2430]]


In [11]:
##Feature Representation
dim=10
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedding_docs)

1/1 [==============================] - 0s 157ms/step


array([[[ 0.02822769,  0.02023902, -0.03934656, -0.04940864,
         -0.02548226, -0.03141075, -0.02283551, -0.04226364,
          0.00766582,  0.03651175],
        [ 0.02822769,  0.02023902, -0.03934656, -0.04940864,
         -0.02548226, -0.03141075, -0.02283551, -0.04226364,
          0.00766582,  0.03651175],
        [ 0.02822769,  0.02023902, -0.03934656, -0.04940864,
         -0.02548226, -0.03141075, -0.02283551, -0.04226364,
          0.00766582,  0.03651175],
        [ 0.02822769,  0.02023902, -0.03934656, -0.04940864,
         -0.02548226, -0.03141075, -0.02283551, -0.04226364,
          0.00766582,  0.03651175],
        [ 0.0454059 ,  0.00702329, -0.00705301,  0.01038563,
         -0.02590351,  0.03109548, -0.04408446,  0.01961576,
          0.01005448, -0.02068372],
        [ 0.00518906,  0.03777012,  0.00282504,  0.04572897,
          0.00467499, -0.0284184 ,  0.00958728,  0.03185603,
         -0.03761375, -0.03771489],
        [ 0.01253771,  0.03168184,  0.00485621, -0.0

In [14]:
embedding_docs[0]

array([   0,    0,    0,    0, 5168, 8796, 4463, 8064])

In [15]:
model.predict(embedding_docs[0])

1/1 [==============================] - 0s 100ms/step


array([[ 0.02822769,  0.02023902, -0.03934656, -0.04940864, -0.02548226,
        -0.03141075, -0.02283551, -0.04226364,  0.00766582,  0.03651175],
       [ 0.02822769,  0.02023902, -0.03934656, -0.04940864, -0.02548226,
        -0.03141075, -0.02283551, -0.04226364,  0.00766582,  0.03651175],
       [ 0.02822769,  0.02023902, -0.03934656, -0.04940864, -0.02548226,
        -0.03141075, -0.02283551, -0.04226364,  0.00766582,  0.03651175],
       [ 0.02822769,  0.02023902, -0.03934656, -0.04940864, -0.02548226,
        -0.03141075, -0.02283551, -0.04226364,  0.00766582,  0.03651175],
       [ 0.0454059 ,  0.00702329, -0.00705301,  0.01038563, -0.02590351,
         0.03109548, -0.04408446,  0.01961576,  0.01005448, -0.02068372],
       [ 0.00518906,  0.03777012,  0.00282504,  0.04572897,  0.00467499,
        -0.0284184 ,  0.00958728,  0.03185603, -0.03761375, -0.03771489],
       [ 0.01253771,  0.03168184,  0.00485621, -0.04058738, -0.0143896 ,
         0.03089852, -0.00267183, -0.01228268