In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent=[
    'the glass of milk',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good',
]

In [3]:
sent

['the glass of milk',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
##Define the vocabulary size
voc_size=10000

In [6]:
one_hot_repr=[one_hot(words, voc_size) for words in sent]
one_hot_repr

[[5168, 8796, 4463, 8064],
 [5168, 3651, 4463, 2617],
 [6780, 8764, 6657, 2430, 7711],
 [6780, 8764, 6657, 2430, 1526],
 [8918, 5168, 5564, 4463, 9717],
 [530, 130, 1909, 2430]]

In [8]:
##Word Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedding_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedding_docs)


[[   0    0    0    0 5168 8796 4463 8064]
 [   0    0    0    0 5168 3651 4463 2617]
 [   0    0    0 6780 8764 6657 2430 7711]
 [   0    0    0 6780 8764 6657 2430 1526]
 [   0    0    0 8918 5168 5564 4463 9717]
 [   0    0    0    0  530  130 1909 2430]]
